"""Taint labels, source provenance, and reader identity definitions.

Inspired by Google's CaMeL paper (arxiv 2503.18813) — data originating from
external or untrusted sources carries a *taint label* through every
transformation so the runtime can enforce information-flow policies before
security-critical operations (terminal exec, message send, memory write).
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from enum import Enum, auto, unique
from typing import FrozenSet

__all__ = [
    "TrustLevel",
    "TaintLabel",
    "default_trust_for",
    "Source",
    "Reader",
]


# ---------------------------------------------------------------------------
# Trust level
# ---------------------------------------------------------------------------

@unique
class TrustLevel(Enum):
    """How much the runtime trusts a particular data source."""

    TRUSTED = auto()
    """Source is fully trusted (e.g. the system prompt itself)."""

    UNTRUSTED = auto()
    """Source is explicitly untrusted (e.g. arbitrary web content)."""

    CONDITIONAL = auto()
    """Trust depends on additional context / policy evaluation."""


# ---------------------------------------------------------------------------
# Taint labels
# ---------------------------------------------------------------------------

@unique
class TaintLabel(Enum):
    """Classification of where a piece of data originated.

    Every value flowing through the agent runtime is tagged with one or more
    of these labels so the flow-control engine can decide whether the value
    may reach a security-sensitive sink.
    """

    USER = auto()
    """Direct user input (chat messages, CLI args)."""

    SYSTEM = auto()
    """System prompt or hard-coded instructions."""

    TOOL_OUTPUT = auto()
    """Return value from a tool invocation."""

    WEB_CONTENT = auto()
    """Data fetched from the open web / browser."""

    FILE_CONTENT = auto()
    """Data read from the local or remote filesystem."""

    MEMORY = auto()
    """Data retrieved from persistent agent memory."""

    MCP = auto()
    """Data received from an MCP (Model Context Protocol) server (generic)."""

    MCP_TOOL_DESCRIPTION = auto()
    """Tool description/metadata from an MCP server tools/list call.
    Higher risk than MCP_TOOL_RESULT — description poisoning is pre-execution."""

    MCP_TOOL_RESULT = auto()
    """Return value from an MCP tools/call invocation."""

    MCP_RESOURCE = auto()
    """Content from an MCP resources/read call."""

    MCP_PROMPT = auto()
    """Prompt template fetched from an MCP prompts/get call."""

    AGENT = auto()
    """Content generated by the LLM itself."""

    AGENT_DELEGATED = auto()
    """Output from a sub-agent or delegated task. May carry injections from
    the sub-agent's environment even if this agent's environment is clean."""

    CROSS_SESSION = auto()
    """Data retrieved from memory that was written in a previous session.
    Cannot be verified against the current session's context."""

    UNKNOWN = auto()
    """Origin cannot be determined — treat as untrusted by default."""


# ---------------------------------------------------------------------------
# Default trust mappings
# ---------------------------------------------------------------------------

_DEFAULT_TRUST: dict[TaintLabel, TrustLevel] = {
    TaintLabel.USER: TrustLevel.TRUSTED,
    TaintLabel.SYSTEM: TrustLevel.TRUSTED,
    TaintLabel.TOOL_OUTPUT: TrustLevel.CONDITIONAL,
    TaintLabel.WEB_CONTENT: TrustLevel.UNTRUSTED,
    TaintLabel.FILE_CONTENT: TrustLevel.CONDITIONAL,
    TaintLabel.MEMORY: TrustLevel.CONDITIONAL,
    TaintLabel.MCP: TrustLevel.UNTRUSTED,
    # Granular MCP labels — tool descriptions are highest risk (pre-execution poisoning)
    TaintLabel.MCP_TOOL_DESCRIPTION: TrustLevel.UNTRUSTED,
    TaintLabel.MCP_TOOL_RESULT: TrustLevel.UNTRUSTED,
    TaintLabel.MCP_RESOURCE: TrustLevel.UNTRUSTED,
    TaintLabel.MCP_PROMPT: TrustLevel.UNTRUSTED,
    TaintLabel.AGENT: TrustLevel.CONDITIONAL,
    TaintLabel.AGENT_DELEGATED: TrustLevel.CONDITIONAL,
    TaintLabel.CROSS_SESSION: TrustLevel.CONDITIONAL,
    TaintLabel.UNKNOWN: TrustLevel.UNTRUSTED,
}


def default_trust_for(label: TaintLabel) -> TrustLevel:
    """Return the default trust level for a given taint label."""
    return _DEFAULT_TRUST.get(label, TrustLevel.UNTRUSTED)


# ---------------------------------------------------------------------------
# Source — records *where* a value came from
# ---------------------------------------------------------------------------

@dataclass(frozen=True, slots=True)
class Source:
    """Provenance record attached to every tainted value.

    Parameters
    ----------
    label:
        The taint classification for this source.
    origin:
        Human-readable identifier — tool name, URL, file path, etc.
    timestamp:
        Unix epoch when the data was ingested.
    trust_level:
        Explicit trust assessment (defaults to the label's default).
    metadata:
        Optional extra context (e.g. HTTP status code, file hash).
    """

    label: TaintLabel
    origin: str = ""
    timestamp: float = field(default_factory=time.time)
    trust_level: TrustLevel = TrustLevel.UNTRUSTED
    metadata: dict[str, str] = field(default_factory=dict, hash=False, compare=False)

    # Convenience factories ---------------------------------------------------

    @classmethod
    def user(cls, origin: str = "user_input", **kwargs: str) -> Source:
        """Create a trusted USER source."""
        return cls(
            label=TaintLabel.USER,
            origin=origin,
            trust_level=TrustLevel.TRUSTED,
            metadata=kwargs,
        )

    @classmethod
    def system(cls, origin: str = "system_prompt", **kwargs: str) -> Source:
        """Create a trusted SYSTEM source."""
        return cls(
            label=TaintLabel.SYSTEM,
            origin=origin,
            trust_level=TrustLevel.TRUSTED,
            metadata=kwargs,
        )

    @classmethod
    def tool(cls, tool_name: str, trust: TrustLevel = TrustLevel.CONDITIONAL, **kwargs: str) -> Source:
        """Create a TOOL_OUTPUT source."""
        return cls(
            label=TaintLabel.TOOL_OUTPUT,
            origin=tool_name,
            trust_level=trust,
            metadata=kwargs,
        )

    @classmethod
    def web(cls, url: str, **kwargs: str) -> Source:
        """Create an untrusted WEB_CONTENT source."""
        return cls(
            label=TaintLabel.WEB_CONTENT,
            origin=url,
            trust_level=TrustLevel.UNTRUSTED,
            metadata=kwargs,
        )

    @classmethod
    def file(cls, path: str, trust: TrustLevel = TrustLevel.CONDITIONAL, **kwargs: str) -> Source:
        """Create a FILE_CONTENT source."""
        return cls(
            label=TaintLabel.FILE_CONTENT,
            origin=path,
            trust_level=trust,
            metadata=kwargs,
        )

    @classmethod
    def mcp(cls, server: str, **kwargs: str) -> Source:
        """Create an untrusted MCP source (generic)."""
        return cls(
            label=TaintLabel.MCP,
            origin=server,
            trust_level=TrustLevel.UNTRUSTED,
            metadata=kwargs,
        )

    @classmethod
    def mcp_tool_description(cls, server: str, tool_name: str = "", **kwargs: str) -> Source:
        """Create an MCP_TOOL_DESCRIPTION source (highest-risk MCP label).

        Tool descriptions are processed before execution and can contain
        instructions that redirect the LLM — the core MCP tool-poisoning attack.
        """
        return cls(
            label=TaintLabel.MCP_TOOL_DESCRIPTION,
            origin=f"{server}::{tool_name}" if tool_name else server,
            trust_level=TrustLevel.UNTRUSTED,
            metadata=kwargs,
        )

    @classmethod
    def mcp_tool_result(cls, server: str, tool_name: str = "", **kwargs: str) -> Source:
        """Create an MCP_TOOL_RESULT source (tool call return value)."""
        return cls(
            label=TaintLabel.MCP_TOOL_RESULT,
            origin=f"{server}::{tool_name}" if tool_name else server,
            trust_level=TrustLevel.UNTRUSTED,
            metadata=kwargs,
        )

    @classmethod
    def agent_delegated(cls, task_id: str = "", **kwargs: str) -> Source:
        """Create an AGENT_DELEGATED source (output from a sub-agent or delegate_task).

        Sub-agent outputs may carry injections from the sub-agent's environment.
        """
        return cls(
            label=TaintLabel.AGENT_DELEGATED,
            origin=task_id or "delegated_task",
            trust_level=TrustLevel.CONDITIONAL,
            metadata=kwargs,
        )

    @classmethod
    def cross_session(cls, session_id: str = "", key: str = "", **kwargs: str) -> Source:
        """Create a CROSS_SESSION source (memory from a previous session).

        Cross-session memory cannot be verified against the current session's
        context — a previous session could have been compromised.
        """
        return cls(
            label=TaintLabel.CROSS_SESSION,
            origin=f"session:{session_id}::{key}" if session_id else key,
            trust_level=TrustLevel.CONDITIONAL,
            metadata=kwargs,
        )

    @classmethod
    def memory(cls, key: str, trust: TrustLevel = TrustLevel.CONDITIONAL, **kwargs: str) -> Source:
        """Create a MEMORY source."""
        return cls(
            label=TaintLabel.MEMORY,
            origin=key,
            trust_level=trust,
            metadata=kwargs,
        )

    @classmethod
    def agent(cls, model: str = "claude", **kwargs: str) -> Source:
        """Create an AGENT source."""
        return cls(
            label=TaintLabel.AGENT,
            origin=model,
            trust_level=TrustLevel.CONDITIONAL,
            metadata=kwargs,
        )

    @classmethod
    def unknown(cls, origin: str = "", **kwargs: str) -> Source:
        """Create an UNKNOWN (untrusted) source."""
        return cls(
            label=TaintLabel.UNKNOWN,
            origin=origin,
            trust_level=TrustLevel.UNTRUSTED,
            metadata=kwargs,
        )


# ---------------------------------------------------------------------------
# Reader — declares *who* may read values with given labels
# ---------------------------------------------------------------------------

@dataclass(frozen=True, slots=True)
class Reader:
    """Access-control principal that declares which taint labels it may read.

    Parameters
    ----------
    identity:
        Unique name of the reader (e.g. ``"terminal"``, ``"user_display"``).
    can_read:
        The set of :class:`TaintLabel` values this reader is allowed to
        consume.  A value whose *every* source label is in ``can_read``
        passes the check; otherwise access is denied.
    """

    identity: str
    can_read: FrozenSet[TaintLabel] = field(default_factory=frozenset)

    def may_access(self, labels: frozenset[TaintLabel]) -> bool:
        """Return ``True`` if all *labels* are in this reader's allowlist."""
        return labels.issubset(self.can_read)

    # Convenience factories ---------------------------------------------------

    @classmethod
    def unrestricted(cls, identity: str) -> Reader:
        """Create a reader that can access all taint labels."""
        return cls(identity=identity, can_read=frozenset(TaintLabel))

    @classmethod
    def trusted_only(cls, identity: str) -> Reader:
        """Create a reader limited to USER and SYSTEM data."""
        return cls(
            identity=identity,
            can_read=frozenset({TaintLabel.USER, TaintLabel.SYSTEM}),
        )
