"""
KatanaInstaller — manages Katana integration into Hermes checkouts.

Combines camelup's approach (lightweight shim installation) with aegis's
patch system (source-level injection).  The installer handles:

- Detection of Hermes checkouts
- Source patch application / reversion
- Configuration file generation
- CA certificate generation for the MITM proxy
- Installation verification and status reporting

Usage::

    installer = KatanaInstaller()

    if installer.detect_hermes("/path/to/hermes"):
        installer.install("/path/to/hermes")
        result = installer.verify("/path/to/hermes")
        print(result.summary)
"""

from __future__ import annotations

__all__ = [
    "BackupManifest",
    "HERMES_MARKERS",
    "KatanaInstaller",
    "VerifyResult",
]


import hashlib
import json
import logging
import shutil
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

from pydantic import BaseModel, Field

from hermes_katana._version import __version__
from hermes_katana.installer.patches import (
    CURRENT_CORE_PATCHES,
    LEGACY_CORE_PATCHES,
    PatchResult,
    PatchStatus,
    _detect_hermes_layout,
    apply_patches,
    get_patch_status,
    preview_apply_patches,
    preview_revert_patches,
    revert_patches,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

KATANA_CONFIG_DIR = ".katana"
KATANA_CONFIG_FILE = "katana.yaml"
KATANA_CA_DIR = "certs"
KATANA_CA_CERT = "katana-ca.pem"
KATANA_CA_KEY = "katana-ca-key.pem"
KATANA_INSTALL_MARKER = ".katana-installed"
KATANA_BACKUP_DIR = ".katana-backups"
KATANA_BACKUP_MANIFEST = "manifest.json"

# Files required for a checkout to be patchable by this installer.
# Legacy layout (Hermes v0.1.0)
HERMES_MARKERS = [
    "hermes/__init__.py",
    "hermes/tools/dispatch.py",
    "hermes/tools/terminal.py",
]

# Current layout markers (post-v0.1.0)
# NB: "hermes_cli" is a directory check to match _detect_hermes_layout() in
# patches.py — keep these in sync, otherwise detect_hermes() and layout
# detection can disagree on edge cases (dir exists without __init__.py).
_HERMES_CURRENT_MARKERS = [
    "tools/registry.py",
    "hermes_cli",
    "tools/terminal_tool.py",
]

# Default configuration template
DEFAULT_CONFIG_TEMPLATE = """\
# HermesKatana Configuration
# Generated by katana install
# https://github.com/hermes-katana

version: "1.0"

# Policy preset: max | balanced | permissive
policy:
  preset: balanced
  custom_dir: null  # Path to custom policy YAML directory

# Scanner settings
scanner:
  block_threshold: 0.7
  warn_threshold: 0.4
  check_injection: true
  check_secrets: true
  check_unicode: true
  check_content: true

# Taint tracking
taint:
  enabled: true
  flow_default: deny  # deny | allow | ask

# MITM Proxy
proxy:
  enabled: true
  listen_host: "127.0.0.1"
  listen_port: 8080
  ca_cert: "{ca_cert_path}"

# Vault
vault:
  backend: keyring  # keyring | encrypted_file
  auto_rotate_days: 90

# Audit
audit:
  enabled: true
  log_allow: true
  trail_dir: "{audit_dir}"
  max_entries: 100000

# Docker integration
docker:
  proxy_forwarding: true
  inject_ca_cert: true
"""


# ---------------------------------------------------------------------------
# Verification result
# ---------------------------------------------------------------------------


class VerifyResult(BaseModel):
    """Result of verifying a Katana installation.

    Attributes:
        is_valid:        Whether the installation is fully valid.
        hermes_detected: Whether the path is a valid Hermes checkout.
        patches_applied: Dict mapping patch name → applied status.
        config_exists:   Whether the katana config file exists.
        ca_cert_exists:  Whether the CA certificate exists.
        marker_exists:   Whether the install marker file exists.
        issues:          List of detected issues.
        warnings:        List of non-critical warnings.
    """

    is_valid: bool = False
    hermes_detected: bool = False
    patches_applied: dict[str, bool] = Field(default_factory=dict)
    config_exists: bool = False
    ca_cert_exists: bool = False
    marker_exists: bool = False
    issues: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)

    @property
    def summary(self) -> str:
        """Human-readable summary of verification results."""
        if self.is_valid:
            return "Installation verified: all checks passed"
        parts = []
        if self.issues:
            parts.append(f"{len(self.issues)} issue(s)")
        if self.warnings:
            parts.append(f"{len(self.warnings)} warning(s)")
        return f"Verification failed: {', '.join(parts)}"

    @property
    def applied_count(self) -> int:
        """Number of patches currently applied."""
        return sum(1 for v in self.patches_applied.values() if v)

    @property
    def total_patches(self) -> int:
        """Total number of expected patches."""
        return len(self.patches_applied)


@dataclass(frozen=True)
class BackupManifest:
    """Metadata for a checkout backup created before install or uninstall."""

    operation: str
    target: str
    backup_root: str
    created_at: str
    files: list[str] = field(default_factory=list)
    missing_paths: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        """Serialize backup manifest to a dictionary."""
        return {
            "operation": self.operation,
            "target": self.target,
            "backup_root": self.backup_root,
            "created_at": self.created_at,
            "files": list(self.files),
            "missing_paths": list(self.missing_paths),
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "BackupManifest":
        """Deserialize backup manifest from a dictionary."""
        return cls(
            operation=str(data["operation"]),
            target=str(data["target"]),
            backup_root=str(data["backup_root"]),
            created_at=str(data["created_at"]),
            files=list(data.get("files", [])),
            missing_paths=list(data.get("missing_paths", [])),
        )


# ---------------------------------------------------------------------------
# KatanaInstaller
# ---------------------------------------------------------------------------


class KatanaInstaller:
    """Manages Katana integration into Hermes checkouts.

    The installer detects Hermes source trees, applies source-code patches,
    generates configuration files, and creates CA certificates for the
    MITM proxy.

    Usage::

        installer = KatanaInstaller()

        # Check if a path is a Hermes checkout
        if installer.detect_hermes("/path/to/hermes"):
            # Install Katana
            installer.install("/path/to/hermes")

            # Verify installation
            result = installer.verify("/path/to/hermes")
            assert result.is_valid

            # Later: uninstall
            installer.uninstall("/path/to/hermes")
    """

    def __init__(self) -> None:
        self._last_backup_manifest: Optional[Path] = None

    @property
    def last_backup_manifest_path(self) -> Optional[Path]:
        """Return the last backup manifest written by this installer."""
        return self._last_backup_manifest

    def _patches_for(self, target: Path) -> list:
        """Return the correct patch list for the Hermes layout at *target*.

        Falls back to the current layout when detection raises (should only
        happen if ``detect_hermes()`` was bypassed) but logs a warning so the
        mismatch is visible instead of silently applying the wrong patches.
        """
        try:
            layout = _detect_hermes_layout(target)
        except ValueError as exc:
            logger.warning(
                "Could not detect Hermes layout at %s (%s); defaulting to current "
                "layout. This usually means detect_hermes() was skipped.",
                target,
                exc,
            )
            layout = "current"
        return LEGACY_CORE_PATCHES if layout == "legacy-v0.1.0" else CURRENT_CORE_PATCHES

    def detect_hermes(self, path: str | Path) -> bool:
        """Check if the given path is a Hermes checkout.

        Looks for known marker files that indicate a Hermes source tree.
        Supports both the legacy (v0.1.0) and current layout.

        Args:
            path: Path to check.

        Returns:
            True if the path appears to be a Hermes checkout.
        """
        target = Path(path).resolve()

        if not target.is_dir():
            logger.debug("Not a directory: %s", target)
            return False

        # Current layout: tools/registry.py + hermes_cli/ (post-v0.1.0)
        current_missing = [m for m in _HERMES_CURRENT_MARKERS if not (target / m).exists()]
        if not current_missing:
            logger.info("Hermes (current layout) detected in %s", target)
            return True

        # Legacy layout: hermes/ top-level package (v0.1.0)
        legacy_missing = [m for m in HERMES_MARKERS if not (target / m).exists()]
        if not legacy_missing:
            logger.info("Hermes (legacy v0.1.0 layout) detected in %s", target)
            return True

        # A pyproject named "hermes" is not sufficient on its own; keep the
        # package-name check only as a secondary signal when the patch targets
        # are present under the expected layout.
        pyproject = target / "pyproject.toml"
        if pyproject.exists():
            try:
                content = pyproject.read_text(encoding="utf-8")
                if (
                    ('name = "hermes"' in content or "name = 'hermes'" in content)
                    and (target / "hermes/tools/dispatch.py").exists()
                    and (target / "hermes/tools/terminal.py").exists()
                ):
                    logger.info("Hermes detected via pyproject.toml in %s", target)
                    return True
            except OSError:
                pass

        logger.debug("Hermes not detected in %s", target)
        return False

    def install(
        self,
        target: str | Path,
        *,
        dry_run: bool = False,
        backup: bool = False,
        backup_dir: str | Path | None = None,
    ) -> list[PatchResult]:
        """Install Katana protection on a Hermes checkout.

        Performs the following steps:
        1. Verify the target is a Hermes checkout.
        2. Create the ``.katana/`` configuration directory.
        3. Generate the default configuration file.
        4. Generate a CA certificate for the MITM proxy.
        5. Apply all source-code patches.
        6. Write the install marker.

        Args:
            target: Path to the Hermes checkout root.
            dry_run: Preview the operation without modifying the checkout.
            backup: Create a pre-change backup manifest and file snapshot.
            backup_dir: Optional explicit backup directory.

        Returns:
            List of :class:`PatchResult` for each patch.

        Raises:
            FileNotFoundError: If the target path does not exist.
            ValueError: If the target is not a Hermes checkout.
        """
        target = Path(target).resolve()
        self._last_backup_manifest = None

        if not target.exists():
            raise FileNotFoundError(f"Target path does not exist: {target}")

        if not self.detect_hermes(target):
            raise ValueError(
                f"Not a Hermes checkout: {target}\n"
                f"Expected current-layout markers: {', '.join(_HERMES_CURRENT_MARKERS)}\n"
                f"Or legacy v0.1.0 markers: {', '.join(HERMES_MARKERS)}"
            )

        # Select patch set based on layout
        try:
            layout = _detect_hermes_layout(target)
        except ValueError:
            layout = "current"  # default to current; detect_hermes already passed

        if layout == "legacy-v0.1.0":
            patches = LEGACY_CORE_PATCHES
            logger.info("Installing Katana on %s (legacy v0.1.0 layout)", target)
        else:
            patches = CURRENT_CORE_PATCHES
            logger.info("Installing Katana on %s (current layout)", target)

        if dry_run:
            return preview_apply_patches(target, patches=patches)

        if backup:
            manifest = self._create_backup(
                target,
                operation="install",
                paths=self._paths_to_backup_for_install(target),
                backup_dir=backup_dir,
            )
            self._last_backup_manifest = Path(manifest.backup_root) / KATANA_BACKUP_MANIFEST
            logger.info("Created install backup at %s", manifest.backup_root)

        # 1. Create .katana directory
        katana_dir = target / KATANA_CONFIG_DIR
        katana_dir.mkdir(exist_ok=True)
        logger.debug("Created config dir: %s", katana_dir)

        # 2. Generate configuration
        self._generate_config(target)

        # 3. Generate CA certificate
        self._generate_ca_cert(target)

        # 4. Apply patches
        results = apply_patches(target, patches=patches)

        # 5. Write install marker
        self._write_marker(target, results)

        # Log summary
        applied = sum(1 for r in results if r.status == PatchStatus.APPLIED)
        skipped = sum(1 for r in results if r.status == PatchStatus.SKIPPED)
        errors = sum(1 for r in results if r.status == PatchStatus.ERROR)

        logger.info(
            "Installation complete: %d applied, %d skipped, %d errors",
            applied,
            skipped,
            errors,
        )

        return results

    def uninstall(
        self,
        target: str | Path,
        *,
        dry_run: bool = False,
        backup: bool = False,
        backup_dir: str | Path | None = None,
    ) -> list[PatchResult]:
        """Remove Katana protection from a Hermes checkout.

        Performs the following steps:
        1. Revert all source-code patches.
        2. Remove the ``.katana/`` directory and all contents.
        3. Remove the install marker.

        Args:
            target: Path to the Hermes checkout root.
            dry_run: Preview the operation without modifying the checkout.
            backup: Create a pre-change backup manifest and file snapshot.
            backup_dir: Optional explicit backup directory.

        Returns:
            List of :class:`PatchResult` for each reverted patch.
        """
        target = Path(target).resolve()
        self._last_backup_manifest = None

        if not target.exists():
            raise FileNotFoundError(f"Target path does not exist: {target}")

        logger.info("Uninstalling Katana from %s", target)

        patches = self._patches_for(target)

        if dry_run:
            return preview_revert_patches(target, patches=patches)

        if backup:
            manifest = self._create_backup(
                target,
                operation="uninstall",
                paths=self._paths_to_backup_for_uninstall(target),
                backup_dir=backup_dir,
            )
            self._last_backup_manifest = Path(manifest.backup_root) / KATANA_BACKUP_MANIFEST
            logger.info("Created uninstall backup at %s", manifest.backup_root)

        # 1. Revert patches
        results = revert_patches(target, patches=patches)

        # 2. Remove .katana directory (reject if it's a symlink to prevent traversal)
        katana_dir = target / KATANA_CONFIG_DIR
        if katana_dir.exists():
            if katana_dir.is_symlink():
                logger.warning("Refusing to remove symlinked config dir: %s", katana_dir)
            else:
                shutil.rmtree(katana_dir)
                logger.debug("Removed config dir: %s", katana_dir)

        # 3. Remove install marker
        marker = target / KATANA_INSTALL_MARKER
        if marker.exists():
            marker.unlink()
            logger.debug("Removed install marker")

        reverted = sum(1 for r in results if r.status == PatchStatus.REVERTED)
        logger.info("Uninstallation complete: %d patches reverted", reverted)

        return results

    def preview_install_actions(self, target: str | Path) -> list[str]:
        """Describe non-patch install actions for dry-run output."""
        target = Path(target).resolve()
        actions: list[str] = []
        katana_dir = target / KATANA_CONFIG_DIR
        config_file = katana_dir / KATANA_CONFIG_FILE
        cert_path = katana_dir / KATANA_CA_DIR / KATANA_CA_CERT
        marker_path = target / KATANA_INSTALL_MARKER

        if not katana_dir.exists():
            actions.append(f"Would create {KATANA_CONFIG_DIR}/")
        if config_file.exists():
            actions.append(f"Would preserve {config_file.relative_to(target)}")
        else:
            actions.append(f"Would write {config_file.relative_to(target)}")
        if cert_path.exists():
            actions.append(f"Would preserve {cert_path.relative_to(target)}")
        else:
            actions.append(f"Would generate {cert_path.relative_to(target)}")
        if marker_path.exists():
            actions.append(f"Would overwrite {marker_path.relative_to(target)}")
        else:
            actions.append(f"Would write {marker_path.relative_to(target)}")
        return actions

    def preview_uninstall_actions(self, target: str | Path) -> list[str]:
        """Describe non-patch uninstall actions for dry-run output."""
        target = Path(target).resolve()
        actions: list[str] = []
        katana_dir = target / KATANA_CONFIG_DIR
        marker_path = target / KATANA_INSTALL_MARKER

        if katana_dir.exists():
            actions.append(f"Would remove {katana_dir.relative_to(target)}/")
        if marker_path.exists():
            actions.append(f"Would remove {marker_path.relative_to(target)}")
        if not actions:
            actions.append("No checkout-local Katana state to remove")
        return actions

    def restore(self, manifest_path: str | Path, *, dry_run: bool = False) -> list[str]:
        """Restore a checkout from a backup manifest."""
        manifest_file = Path(manifest_path).expanduser().resolve()
        if not manifest_file.exists():
            raise FileNotFoundError(f"Backup manifest does not exist: {manifest_file}")

        try:
            raw = json.loads(manifest_file.read_text(encoding="utf-8"))
            manifest = BackupManifest.from_dict(raw)
        except (json.JSONDecodeError, OSError, KeyError) as exc:
            raise ValueError(f"Invalid backup manifest: {manifest_file}") from exc

        target = Path(manifest.target).resolve()
        backup_root = Path(manifest.backup_root).resolve()
        actions: list[str] = []

        def _validate_containment(path: Path, container: Path, label: str) -> None:
            """Ensure resolved path stays within container."""
            try:
                path.resolve().relative_to(container)
            except ValueError:
                raise ValueError(f"{label} path escapes container: {path} is not under {container}")
            # Reject symlinks that could redirect operations
            if path.is_symlink():
                raise ValueError(f"{label} path is a symlink: {path}")

        for relative_raw in manifest.files:
            relative = Path(relative_raw)
            # Reject absolute paths and traversal
            if relative.is_absolute() or ".." in relative.parts:
                raise ValueError(f"Manifest contains unsafe path: {relative_raw}")
            source = backup_root / relative
            destination = target / relative
            _validate_containment(source, backup_root, "Source")
            _validate_containment(destination, target, "Destination")
            actions.append(f"Restore {relative.as_posix()}")

            if dry_run:
                continue

            if source.is_dir():
                shutil.copytree(source, destination, dirs_exist_ok=True)
            else:
                destination.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(source, destination)

        for relative_raw in manifest.missing_paths:
            relative = Path(relative_raw)
            if relative.is_absolute() or ".." in relative.parts:
                raise ValueError(f"Manifest contains unsafe missing_path: {relative_raw}")
            destination = target / relative
            _validate_containment(destination, target, "Remove target")
            if destination.exists():
                actions.append(f"Remove {relative.as_posix()}")
                if dry_run:
                    continue
                if destination.is_dir():
                    shutil.rmtree(destination)
                else:
                    destination.unlink()

        return actions

    def verify(self, target: str | Path) -> VerifyResult:
        """Verify the integrity of a Katana installation.

        Checks all components: Hermes detection, patch status, config
        file, CA certificate, and install marker.

        Args:
            target: Path to the Hermes checkout root.

        Returns:
            A :class:`VerifyResult` with detailed status information.
        """
        target = Path(target).resolve()
        result = VerifyResult()

        # Check Hermes
        result.hermes_detected = self.detect_hermes(target)
        if not result.hermes_detected:
            result.issues.append("Not a Hermes checkout")
            return result

        # Check patches
        patches = self._patches_for(target)
        result.patches_applied = get_patch_status(target, patches=patches)
        for patch_name, applied in result.patches_applied.items():
            if not applied:
                # Check if the patch is critical
                patch = next((p for p in patches if p.name == patch_name), None)
                if patch and patch.critical:
                    result.issues.append(f"Critical patch not applied: {patch_name}")
                else:
                    result.warnings.append(f"Optional patch not applied: {patch_name}")

        # Check config
        config_file = target / KATANA_CONFIG_DIR / KATANA_CONFIG_FILE
        result.config_exists = config_file.exists()
        if not result.config_exists:
            result.issues.append("Configuration file missing")

        # Check CA cert
        ca_cert = target / KATANA_CONFIG_DIR / KATANA_CA_DIR / KATANA_CA_CERT
        result.ca_cert_exists = ca_cert.exists()
        if not result.ca_cert_exists:
            result.warnings.append("CA certificate missing (proxy may not work)")

        # Check marker
        marker = target / KATANA_INSTALL_MARKER
        result.marker_exists = marker.exists()
        if not result.marker_exists:
            result.warnings.append("Install marker missing")

        # Overall validity
        result.is_valid = len(result.issues) == 0

        return result

    def status(self, target: str | Path) -> dict[str, Any]:
        """Get comprehensive installation status.

        Returns a dict with all status information suitable for
        display or serialization.

        Args:
            target: Path to the Hermes checkout root.

        Returns:
            Dict with keys: hermes_detected, installed, patches, config,
            ca_cert, marker, verify_result.
        """
        target = Path(target).resolve()
        verify = self.verify(target)

        # Read marker metadata if available
        marker_data: dict[str, Any] = {}
        marker_path = target / KATANA_INSTALL_MARKER
        if marker_path.exists():
            try:
                marker_data = json.loads(marker_path.read_text(encoding="utf-8"))
            except (json.JSONDecodeError, OSError):
                marker_data = {"error": "Could not read marker file"}

        return {
            "target": str(target),
            "hermes_detected": verify.hermes_detected,
            "installed": verify.marker_exists,
            "is_valid": verify.is_valid,
            "patches": {
                "applied": verify.applied_count,
                "total": verify.total_patches,
                "details": verify.patches_applied,
            },
            "config_exists": verify.config_exists,
            "ca_cert_exists": verify.ca_cert_exists,
            "issues": verify.issues,
            "warnings": verify.warnings,
            "install_metadata": marker_data,
        }

    # -- Private helpers ----------------------------------------------------

    def _paths_to_backup_for_install(self, target: Path) -> list[Path]:
        """Collect files and directories to snapshot before install."""
        paths: list[Path] = []
        seen: set[Path] = set()

        for patch in self._patches_for(target):
            candidate = target / patch.target_file
            if candidate.exists() and candidate not in seen:
                paths.append(candidate)
                seen.add(candidate)

        for candidate in (
            target / KATANA_CONFIG_DIR,
            target / KATANA_INSTALL_MARKER,
        ):
            if candidate.exists() and candidate not in seen:
                paths.append(candidate)
                seen.add(candidate)

        return paths

    def _paths_to_backup_for_uninstall(self, target: Path) -> list[Path]:
        """Collect files and directories to snapshot before uninstall."""
        return self._paths_to_backup_for_install(target)

    def _create_backup(
        self,
        target: Path,
        *,
        operation: str,
        paths: list[Path],
        backup_dir: str | Path | None = None,
    ) -> BackupManifest:
        """Create a file snapshot and manifest for install or uninstall."""
        if backup_dir is None:
            timestamp = time.strftime("%Y%m%d-%H%M%S", time.gmtime())
            root = target / KATANA_BACKUP_DIR / f"{operation}-{timestamp}"
        else:
            root = Path(backup_dir).expanduser().resolve()

        if root.exists() and any(root.iterdir()):
            raise FileExistsError(f"Backup directory is not empty: {root}")

        root.mkdir(parents=True, exist_ok=True)
        copied: list[str] = []

        for source in paths:
            relative = source.relative_to(target)
            destination = root / relative

            if source.is_dir():
                shutil.copytree(source, destination, dirs_exist_ok=True)
            else:
                destination.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(source, destination)

            copied.append(relative.as_posix())

        manifest = BackupManifest(
            operation=operation,
            target=str(target),
            backup_root=str(root),
            created_at=time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            files=sorted(copied),
            missing_paths=sorted(self._missing_paths_for_backup(target, operation)),
        )
        manifest_path = root / KATANA_BACKUP_MANIFEST
        manifest_path.write_text(json.dumps(manifest.to_dict(), indent=2), encoding="utf-8")
        return manifest

    def _missing_paths_for_backup(self, target: Path, operation: str) -> list[str]:
        """Describe paths that did not exist when the backup was taken."""
        if operation != "install":
            return []

        expected = [
            target / KATANA_CONFIG_DIR,
            target / KATANA_INSTALL_MARKER,
        ]
        return [path.relative_to(target).as_posix() for path in expected if not path.exists()]

    def _generate_config(self, target: Path) -> None:
        """Generate the default Katana configuration file.

        Does not overwrite an existing config file — preserves user
        customizations.
        """
        config_dir = target / KATANA_CONFIG_DIR
        config_file = config_dir / KATANA_CONFIG_FILE

        if config_file.exists():
            logger.debug("Config file already exists, skipping: %s", config_file)
            return

        ca_cert_path = (Path(KATANA_CONFIG_DIR) / KATANA_CA_DIR / KATANA_CA_CERT).as_posix()
        audit_dir = (Path(KATANA_CONFIG_DIR) / "audit").as_posix()

        content = DEFAULT_CONFIG_TEMPLATE.format(
            ca_cert_path=ca_cert_path,
            audit_dir=audit_dir,
        )

        config_file.write_text(content, encoding="utf-8")
        logger.info("Generated config: %s", config_file)

        # Create audit directory
        (config_dir / "audit").mkdir(exist_ok=True)

    def _generate_ca_cert(self, target: Path) -> None:
        """Generate a CA certificate for the MITM proxy.

        Uses the ``cryptography`` library to create a self-signed CA
        certificate and private key.  Skips if the cert already exists.
        """
        cert_dir = target / KATANA_CONFIG_DIR / KATANA_CA_DIR
        cert_dir.mkdir(parents=True, exist_ok=True)

        cert_path = cert_dir / KATANA_CA_CERT
        key_path = cert_dir / KATANA_CA_KEY

        if cert_path.exists() and key_path.exists():
            logger.debug("CA cert already exists, skipping: %s", cert_path)
            return

        try:
            from cryptography import x509
            from cryptography.hazmat.primitives import hashes, serialization
            from cryptography.hazmat.primitives.asymmetric import rsa
            from cryptography.x509.oid import NameOID
            import datetime

            # Generate RSA key
            key = rsa.generate_private_key(
                public_exponent=65537,
                key_size=2048,
            )

            # Build CA certificate
            subject = issuer = x509.Name(
                [
                    x509.NameAttribute(NameOID.COUNTRY_NAME, "US"),
                    x509.NameAttribute(NameOID.ORGANIZATION_NAME, "HermesKatana"),
                    x509.NameAttribute(NameOID.COMMON_NAME, "HermesKatana CA"),
                ]
            )

            cert = (
                x509.CertificateBuilder()
                .subject_name(subject)
                .issuer_name(issuer)
                .public_key(key.public_key())
                .serial_number(x509.random_serial_number())
                .not_valid_before(datetime.datetime.now(datetime.timezone.utc))
                .not_valid_after(datetime.datetime.now(datetime.timezone.utc) + datetime.timedelta(days=3650))
                .add_extension(
                    x509.BasicConstraints(ca=True, path_length=0),
                    critical=True,
                )
                .add_extension(
                    x509.KeyUsage(
                        digital_signature=True,
                        key_cert_sign=True,
                        crl_sign=True,
                        content_commitment=False,
                        key_encipherment=False,
                        data_encipherment=False,
                        key_agreement=False,
                        encipher_only=False,
                        decipher_only=False,
                    ),
                    critical=True,
                )
                .sign(key, hashes.SHA256())
            )

            # Write certificate
            cert_path.write_bytes(cert.public_bytes(serialization.Encoding.PEM))

            # Write private key (encrypted with a passphrase derived from install path + random salt)
            import secrets as _secrets

            ca_salt = _secrets.token_hex(16)
            salt_path = cert_dir / "ca_salt.txt"
            salt_path.write_text(ca_salt, encoding="utf-8")
            passphrase = hashlib.sha256(f"katana-{target}-{ca_salt}".encode()).hexdigest()[:32].encode()

            key_path.write_bytes(
                key.private_bytes(
                    encoding=serialization.Encoding.PEM,
                    format=serialization.PrivateFormat.PKCS8,
                    encryption_algorithm=serialization.BestAvailableEncryption(passphrase),
                )
            )

            # Restrict key file permissions
            try:
                key_path.chmod(0o600)
            except OSError:
                pass  # Windows doesn't support Unix permissions

            logger.info("Generated CA certificate: %s", cert_path)

        except ImportError:
            logger.warning(
                "cryptography library not available — CA cert not generated. Install with: pip install cryptography"
            )
        except Exception:
            logger.exception("Failed to generate CA certificate")

    def _write_marker(self, target: Path, results: list[PatchResult]) -> None:
        """Write the install marker file with metadata."""
        marker = target / KATANA_INSTALL_MARKER
        data = {
            "installed_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "installer_version": __version__,
            "patches": {r.name: {"status": r.status.value, "message": r.message} for r in results},
            "target": str(target),
        }
        if self._last_backup_manifest is not None:
            data["backup_manifest"] = str(self._last_backup_manifest)
        marker.write_text(json.dumps(data, indent=2), encoding="utf-8")
        logger.debug("Wrote install marker: %s", marker)
