"""
KatanaInstaller — manages Katana integration into Hermes checkouts.

Combines camelup's approach (lightweight shim installation) with aegis's
patch system (source-level injection).  The installer handles:

- Detection of Hermes checkouts
- Source patch application / reversion
- Configuration file generation
- CA certificate generation for the MITM proxy
- Installation verification and status reporting

Usage::

    installer = KatanaInstaller()

    if installer.detect_hermes("/path/to/hermes"):
        installer.install("/path/to/hermes")
        result = installer.verify("/path/to/hermes")
        print(result.summary)
"""

from __future__ import annotations

import hashlib
import json
import logging
import os
import shutil
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

from pydantic import BaseModel, Field

from hermes_katana.installer.patches import (
    CORE_PATCHES,
    PatchResult,
    PatchStatus,
    apply_patches,
    get_patch_status,
    revert_patches,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

KATANA_CONFIG_DIR = ".katana"
KATANA_CONFIG_FILE = "katana.yaml"
KATANA_CA_DIR = "certs"
KATANA_CA_CERT = "katana-ca.pem"
KATANA_CA_KEY = "katana-ca-key.pem"
KATANA_INSTALL_MARKER = ".katana-installed"

# Files that indicate a Hermes checkout
HERMES_MARKERS = [
    "hermes/__init__.py",
    "hermes/tools/dispatch.py",
    "pyproject.toml",
]

# Alternative markers (some Hermes forks use different layouts)
HERMES_ALT_MARKERS = [
    "src/hermes/__init__.py",
    "hermes/core/agent.py",
    "hermes/agent.py",
]

# Default configuration template
DEFAULT_CONFIG_TEMPLATE = """\
# HermesKatana Configuration
# Generated by katana install
# https://github.com/hermes-katana

version: "1.0"

# Policy preset: paranoid | balanced | permissive
policy:
  preset: balanced
  custom_dir: null  # Path to custom policy YAML directory

# Scanner settings
scanner:
  block_threshold: 0.7
  warn_threshold: 0.4
  check_injection: true
  check_secrets: true
  check_unicode: true
  check_content: true

# Taint tracking
taint:
  enabled: true
  flow_default: deny  # deny | allow | ask

# MITM Proxy
proxy:
  enabled: true
  listen_host: "127.0.0.1"
  listen_port: 8080
  ca_cert: "{ca_cert_path}"

# Vault
vault:
  backend: keyring  # keyring | encrypted_file
  auto_rotate_days: 90

# Audit
audit:
  enabled: true
  log_allow: true
  trail_dir: "{audit_dir}"
  max_entries: 100000

# Docker integration
docker:
  proxy_forwarding: true
  inject_ca_cert: true
"""


# ---------------------------------------------------------------------------
# Verification result
# ---------------------------------------------------------------------------


class VerifyResult(BaseModel):
    """Result of verifying a Katana installation.

    Attributes:
        is_valid:        Whether the installation is fully valid.
        hermes_detected: Whether the path is a valid Hermes checkout.
        patches_applied: Dict mapping patch name → applied status.
        config_exists:   Whether the katana config file exists.
        ca_cert_exists:  Whether the CA certificate exists.
        marker_exists:   Whether the install marker file exists.
        issues:          List of detected issues.
        warnings:        List of non-critical warnings.
    """

    is_valid: bool = False
    hermes_detected: bool = False
    patches_applied: dict[str, bool] = Field(default_factory=dict)
    config_exists: bool = False
    ca_cert_exists: bool = False
    marker_exists: bool = False
    issues: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)

    @property
    def summary(self) -> str:
        """Human-readable summary of verification results."""
        if self.is_valid:
            return "Installation verified: all checks passed"
        parts = []
        if self.issues:
            parts.append(f"{len(self.issues)} issue(s)")
        if self.warnings:
            parts.append(f"{len(self.warnings)} warning(s)")
        return f"Verification failed: {', '.join(parts)}"

    @property
    def applied_count(self) -> int:
        """Number of patches currently applied."""
        return sum(1 for v in self.patches_applied.values() if v)

    @property
    def total_patches(self) -> int:
        """Total number of expected patches."""
        return len(self.patches_applied)


# ---------------------------------------------------------------------------
# KatanaInstaller
# ---------------------------------------------------------------------------


class KatanaInstaller:
    """Manages Katana integration into Hermes checkouts.

    The installer detects Hermes source trees, applies source-code patches,
    generates configuration files, and creates CA certificates for the
    MITM proxy.

    Usage::

        installer = KatanaInstaller()

        # Check if a path is a Hermes checkout
        if installer.detect_hermes("/path/to/hermes"):
            # Install Katana
            installer.install("/path/to/hermes")

            # Verify installation
            result = installer.verify("/path/to/hermes")
            assert result.is_valid

            # Later: uninstall
            installer.uninstall("/path/to/hermes")
    """

    def detect_hermes(self, path: str | Path) -> bool:
        """Check if the given path is a Hermes checkout.

        Looks for known marker files that indicate a Hermes source tree.
        Supports both standard and alternative directory layouts.

        Args:
            path: Path to check.

        Returns:
            True if the path appears to be a Hermes checkout.
        """
        target = Path(path).resolve()

        if not target.is_dir():
            logger.debug("Not a directory: %s", target)
            return False

        # Check standard markers
        for marker in HERMES_MARKERS:
            if (target / marker).exists():
                logger.info("Hermes detected via %s in %s", marker, target)
                return True

        # Check alternative layouts
        for marker in HERMES_ALT_MARKERS:
            if (target / marker).exists():
                logger.info("Hermes (alt layout) detected via %s in %s", marker, target)
                return True

        # Check pyproject.toml for hermes package name
        pyproject = target / "pyproject.toml"
        if pyproject.exists():
            try:
                content = pyproject.read_text(encoding="utf-8")
                if 'name = "hermes"' in content or "name = 'hermes'" in content:
                    logger.info("Hermes detected via pyproject.toml in %s", target)
                    return True
            except OSError:
                pass

        logger.debug("Hermes not detected in %s", target)
        return False

    def install(self, target: str | Path) -> list[PatchResult]:
        """Install Katana protection on a Hermes checkout.

        Performs the following steps:
        1. Verify the target is a Hermes checkout.
        2. Create the ``.katana/`` configuration directory.
        3. Generate the default configuration file.
        4. Generate a CA certificate for the MITM proxy.
        5. Apply all source-code patches.
        6. Write the install marker.

        Args:
            target: Path to the Hermes checkout root.

        Returns:
            List of :class:`PatchResult` for each patch.

        Raises:
            FileNotFoundError: If the target path does not exist.
            ValueError: If the target is not a Hermes checkout.
        """
        target = Path(target).resolve()

        if not target.exists():
            raise FileNotFoundError(f"Target path does not exist: {target}")

        if not self.detect_hermes(target):
            raise ValueError(
                f"Not a Hermes checkout: {target}\n"
                f"Expected marker files: {', '.join(HERMES_MARKERS)}"
            )

        logger.info("Installing Katana on %s", target)

        # 1. Create .katana directory
        katana_dir = target / KATANA_CONFIG_DIR
        katana_dir.mkdir(exist_ok=True)
        logger.debug("Created config dir: %s", katana_dir)

        # 2. Generate configuration
        self._generate_config(target)

        # 3. Generate CA certificate
        self._generate_ca_cert(target)

        # 4. Apply patches
        results = apply_patches(target)

        # 5. Write install marker
        self._write_marker(target, results)

        # Log summary
        applied = sum(1 for r in results if r.status == PatchStatus.APPLIED)
        skipped = sum(1 for r in results if r.status == PatchStatus.SKIPPED)
        errors = sum(1 for r in results if r.status == PatchStatus.ERROR)

        logger.info(
            "Installation complete: %d applied, %d skipped, %d errors",
            applied,
            skipped,
            errors,
        )

        return results

    def uninstall(self, target: str | Path) -> list[PatchResult]:
        """Remove Katana protection from a Hermes checkout.

        Performs the following steps:
        1. Revert all source-code patches.
        2. Remove the ``.katana/`` directory and all contents.
        3. Remove the install marker.

        Args:
            target: Path to the Hermes checkout root.

        Returns:
            List of :class:`PatchResult` for each reverted patch.
        """
        target = Path(target).resolve()

        if not target.exists():
            raise FileNotFoundError(f"Target path does not exist: {target}")

        logger.info("Uninstalling Katana from %s", target)

        # 1. Revert patches
        results = revert_patches(target)

        # 2. Remove .katana directory
        katana_dir = target / KATANA_CONFIG_DIR
        if katana_dir.exists():
            shutil.rmtree(katana_dir)
            logger.debug("Removed config dir: %s", katana_dir)

        # 3. Remove install marker
        marker = target / KATANA_INSTALL_MARKER
        if marker.exists():
            marker.unlink()
            logger.debug("Removed install marker")

        reverted = sum(1 for r in results if r.status == PatchStatus.REVERTED)
        logger.info("Uninstallation complete: %d patches reverted", reverted)

        return results

    def verify(self, target: str | Path) -> VerifyResult:
        """Verify the integrity of a Katana installation.

        Checks all components: Hermes detection, patch status, config
        file, CA certificate, and install marker.

        Args:
            target: Path to the Hermes checkout root.

        Returns:
            A :class:`VerifyResult` with detailed status information.
        """
        target = Path(target).resolve()
        result = VerifyResult()

        # Check Hermes
        result.hermes_detected = self.detect_hermes(target)
        if not result.hermes_detected:
            result.issues.append("Not a Hermes checkout")
            return result

        # Check patches
        result.patches_applied = get_patch_status(target)
        for patch_name, applied in result.patches_applied.items():
            if not applied:
                # Check if the patch is critical
                patch = next((p for p in CORE_PATCHES if p.name == patch_name), None)
                if patch and patch.critical:
                    result.issues.append(f"Critical patch not applied: {patch_name}")
                else:
                    result.warnings.append(f"Optional patch not applied: {patch_name}")

        # Check config
        config_file = target / KATANA_CONFIG_DIR / KATANA_CONFIG_FILE
        result.config_exists = config_file.exists()
        if not result.config_exists:
            result.issues.append("Configuration file missing")

        # Check CA cert
        ca_cert = target / KATANA_CONFIG_DIR / KATANA_CA_DIR / KATANA_CA_CERT
        result.ca_cert_exists = ca_cert.exists()
        if not result.ca_cert_exists:
            result.warnings.append("CA certificate missing (proxy may not work)")

        # Check marker
        marker = target / KATANA_INSTALL_MARKER
        result.marker_exists = marker.exists()
        if not result.marker_exists:
            result.warnings.append("Install marker missing")

        # Overall validity
        result.is_valid = len(result.issues) == 0

        return result

    def status(self, target: str | Path) -> dict[str, Any]:
        """Get comprehensive installation status.

        Returns a dict with all status information suitable for
        display or serialization.

        Args:
            target: Path to the Hermes checkout root.

        Returns:
            Dict with keys: hermes_detected, installed, patches, config,
            ca_cert, marker, verify_result.
        """
        target = Path(target).resolve()
        verify = self.verify(target)

        # Read marker metadata if available
        marker_data: dict[str, Any] = {}
        marker_path = target / KATANA_INSTALL_MARKER
        if marker_path.exists():
            try:
                marker_data = json.loads(marker_path.read_text(encoding="utf-8"))
            except (json.JSONDecodeError, OSError):
                marker_data = {"error": "Could not read marker file"}

        return {
            "target": str(target),
            "hermes_detected": verify.hermes_detected,
            "installed": verify.marker_exists,
            "is_valid": verify.is_valid,
            "patches": {
                "applied": verify.applied_count,
                "total": verify.total_patches,
                "details": verify.patches_applied,
            },
            "config_exists": verify.config_exists,
            "ca_cert_exists": verify.ca_cert_exists,
            "issues": verify.issues,
            "warnings": verify.warnings,
            "install_metadata": marker_data,
        }

    # -- Private helpers ----------------------------------------------------

    def _generate_config(self, target: Path) -> None:
        """Generate the default Katana configuration file.

        Does not overwrite an existing config file — preserves user
        customizations.
        """
        config_dir = target / KATANA_CONFIG_DIR
        config_file = config_dir / KATANA_CONFIG_FILE

        if config_file.exists():
            logger.debug("Config file already exists, skipping: %s", config_file)
            return

        ca_cert_path = str(config_dir / KATANA_CA_DIR / KATANA_CA_CERT)
        audit_dir = str(config_dir / "audit")

        content = DEFAULT_CONFIG_TEMPLATE.format(
            ca_cert_path=ca_cert_path,
            audit_dir=audit_dir,
        )

        config_file.write_text(content, encoding="utf-8")
        logger.info("Generated config: %s", config_file)

        # Create audit directory
        (config_dir / "audit").mkdir(exist_ok=True)

    def _generate_ca_cert(self, target: Path) -> None:
        """Generate a CA certificate for the MITM proxy.

        Uses the ``cryptography`` library to create a self-signed CA
        certificate and private key.  Skips if the cert already exists.
        """
        cert_dir = target / KATANA_CONFIG_DIR / KATANA_CA_DIR
        cert_dir.mkdir(parents=True, exist_ok=True)

        cert_path = cert_dir / KATANA_CA_CERT
        key_path = cert_dir / KATANA_CA_KEY

        if cert_path.exists() and key_path.exists():
            logger.debug("CA cert already exists, skipping: %s", cert_path)
            return

        try:
            from cryptography import x509
            from cryptography.hazmat.primitives import hashes, serialization
            from cryptography.hazmat.primitives.asymmetric import rsa
            from cryptography.x509.oid import NameOID
            import datetime

            # Generate RSA key
            key = rsa.generate_private_key(
                public_exponent=65537,
                key_size=2048,
            )

            # Build CA certificate
            subject = issuer = x509.Name([
                x509.NameAttribute(NameOID.COUNTRY_NAME, "US"),
                x509.NameAttribute(NameOID.ORGANIZATION_NAME, "HermesKatana"),
                x509.NameAttribute(NameOID.COMMON_NAME, "HermesKatana CA"),
            ])

            cert = (
                x509.CertificateBuilder()
                .subject_name(subject)
                .issuer_name(issuer)
                .public_key(key.public_key())
                .serial_number(x509.random_serial_number())
                .not_valid_before(datetime.datetime.now(datetime.timezone.utc))
                .not_valid_after(
                    datetime.datetime.now(datetime.timezone.utc)
                    + datetime.timedelta(days=3650)
                )
                .add_extension(
                    x509.BasicConstraints(ca=True, path_length=0),
                    critical=True,
                )
                .add_extension(
                    x509.KeyUsage(
                        digital_signature=True,
                        key_cert_sign=True,
                        crl_sign=True,
                        content_commitment=False,
                        key_encipherment=False,
                        data_encipherment=False,
                        key_agreement=False,
                        encipher_only=False,
                        decipher_only=False,
                    ),
                    critical=True,
                )
                .sign(key, hashes.SHA256())
            )

            # Write certificate
            cert_path.write_bytes(cert.public_bytes(serialization.Encoding.PEM))

            # Write private key (encrypted with a passphrase derived from install path)
            passphrase = hashlib.sha256(
                f"katana-{target}".encode()
            ).hexdigest()[:32].encode()

            key_path.write_bytes(
                key.private_bytes(
                    encoding=serialization.Encoding.PEM,
                    format=serialization.PrivateFormat.PKCS8,
                    encryption_algorithm=serialization.BestAvailableEncryption(passphrase),
                )
            )

            # Restrict key file permissions
            try:
                key_path.chmod(0o600)
            except OSError:
                pass  # Windows doesn't support Unix permissions

            logger.info("Generated CA certificate: %s", cert_path)

        except ImportError:
            logger.warning(
                "cryptography library not available — CA cert not generated. "
                "Install with: pip install cryptography"
            )
        except Exception:
            logger.exception("Failed to generate CA certificate")

    def _write_marker(self, target: Path, results: list[PatchResult]) -> None:
        """Write the install marker file with metadata."""
        marker = target / KATANA_INSTALL_MARKER
        data = {
            "installed_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "installer_version": "0.1.0",
            "patches": {
                r.name: {"status": r.status.value, "message": r.message}
                for r in results
            },
            "target": str(target),
        }
        marker.write_text(json.dumps(data, indent=2), encoding="utf-8")
        logger.debug("Wrote install marker: %s", marker)
